version: '3.7'
services:
  rq-dashboard:
    image: anandsaha/rq-docker:0.0.3
    command: rq-dashboard -H rq-server
    ports:
      - 9181:9181
    depends_on:
      - rq-server
      - rq-worker

  rq-worker:
    image: anandsaha/rq-docker:0.0.3
    command: rq worker -u redis://rq-server:6379 high normal low
    deploy:
      replicas: 3
    depends_on:
      - rq-server

  rq-server:
    image: redis:5.0.9-alpine
